spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}AYAke0Hjg6BjHyCtc1QEzmDS3SGa6zsG0Q6/gETFNUKIhiHvQBsh6V/+olFs+FPIZt7nYtcqNon3nsuj7hAXDDIC5CYjB8ogEfavhKhw123xc6eQ/jwCdfUoUdK6tIt9AlE/aC0ulMpT4Oa5w1xbWP2IrT3TfRMboDPaALz06yQbiIpm3+p93h/nFZzT/lFb235HoMiVDYvEcYPrSqyek06FBlI6o7gScNGEzKWl335t18CDJWhQbIUqWVl2w/R0ZtvPLxdysmzCOkSzMeGKTWf4fERjYPBgpZMJXz1ziSskc8q7N8pvCr/0CvUh9Ot9BoKq7ERMFPxsHmm5XeyhegDMTiBCmrk4PugRfQ2RcVWoke0SjG6B8uMoAFXeCqYp0nL3EAqnn/08AT71hatp5sYuABmgrKbIhI5MiG+6Rw3wM3gGErRoGwP2l0BCAyJCPRnFTTEy7AuYMKUkQ1yO+XF4BJaPvSZ1SQybu8vPrCGsXEKbcbn/Z+e0W3nYd6ox0774ua7s9xmURnjcTIc5kudP0TWIPEYUzw1tqAymhJF20drYUHFDv/iiLdI3swOCzTUgTN98RfY1Jv2D/sH3PHQk/xiAQbT+t/k6EILiRr8ecg=='
gateway:
  ip: 127.0.0.1

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's order is empty.
